/* P0 — Pizzeria source-of-truth configuration. Interaction engine remains inherited from Class 04. */
const PM=window.PizzeriaMedia||{
  brand:{logo:'https://placehold.co/360x120/111111/f3efe6?text=PIZZA+LAB'},
  sections:{hero:'https://placehold.co/1920x1080/171714/f3efe6?text=PIZZERIA+HERO+PLACEHOLDER',origin:'https://placehold.co/1200x1500/211d18/f3efe6?text=DOUGH+%2B+FIRE',atmosphere:'https://placehold.co/1920x1080/151515/f3efe6?text=PIZZERIA+ATMOSPHERE',chef:'https://placehold.co/1200x1500/1b1a18/f3efe6?text=PIZZAIOLO'},
  pizzas:{margherita:'https://placehold.co/1200x1200/16110e/f3efe6?text=MARGHERITA',diavola:'https://placehold.co/1200x1200/1c0f0d/f3efe6?text=DIAVOLA',mortadella:'https://placehold.co/1200x1200/171513/f3efe6?text=MORTADELLA',tartufo:'https://placehold.co/1200x1200/171611/f3efe6?text=TARTUFO',marinara:'https://placehold.co/1200x1200/15100d/f3efe6?text=MARINARA',quattro:'https://placehold.co/1200x1200/17140f/f3efe6?text=QUATTRO+FORMAGGI'}
};
window.RestaurantDefaults={
  id:'pizzeria-p0',schemaVersion:4,status:'draft',
  brand:{name:'PIZZA LAB',logoText:'PIZZA LAB',accent:'#ff5b35',ink:'#090908',paper:'#eee5d8',fontDisplay:'Italiana',fontBody:'DM Sans'},
  header:{links:[['Pizzas','#signature'],['Story','#story'],['Experience','#experience'],['Visit','#visit']],studioLabel:'Pizzeria Studio',reserveLabel:'Pedir / Reservar'},
  hero:{kicker:'P0 · Pizzeria immersive foundation',line1:'PIZZA',line2:'is the interface.',body:'Una pizzería demo construida sobre el motor premium existente. Hoy usamos placeholders; después sustituiremos cada slot por fotografía y vídeo premium.',cta:'Explorar pizzas',stamp:'PIZZA LAB · P0 · NO 3D ·',scroll:'SCROLL TO ENTER'},
  philosophy:{index:'01 / Foundation',title:'Antes del horno, necesitamos una pizzería que ya funcione.',body1:'Este P0 transforma la plataforma de restauración heredada en una base específica para pizza sin reescribir el motor. Conservamos navegación, motion, Studio, persistencia, responsive y detalle de producto.',body2:'Los assets actuales son placeholders deliberados y están centralizados. La dirección de arte premium llegará después, sin tocar la lógica de interacción.'},
  orbital:{index:'02 / Pizza selection',kicker:'Drag · wheel · swipe · arrows',title:'Choose your pizza',explore:'Explore pizza'},
  origin:{index:'03 / Dough & fire',title:'Flour. Water. Time. Fire.',body:'La historia de producto se reorganiza alrededor de masa, fermentación, ingredientes y horno. Este bloque será una de las bases narrativas para el futuro Oven POC.',caption:'48H FERMENTATION · PLACEHOLDER'},
  atmosphere:{index:'04 / Experience',title:'Pizza should feel alive.',caption:'PIZZERIA · PLACEHOLDER',body:'El sistema debe ser útil como web real y, al mismo tiempo, convertir el descubrimiento de pizza en una experiencia interactiva memorable.',cta:'Pedir / reservar →'},
  chef:{index:'05 / Pizzaiolo',title:'Craft before spectacle.',quote:'“Primero una pizza creíble. Después hacemos magia con ella.”',badges:['48h dough','High heat','Seasonal toppings']},
  visit:{kicker:'Alicante · Demo P0',title:'Your table. Your pizza.',cta:'Pedir / reservar',addressLabel:'Address',address:'Dirección placeholder · Alicante',serviceLabel:'Service',service:'13:00 — 00:00',contactLabel:'Contact',contact:'hello@pizzalab.demo',bookingUrl:'#'},
  footer:{left:'PIZZA LAB',center:'P0 · Pizzeria Foundation',right:'Premium media pending'},
  media:{logo:{type:'image',url:PM.brand.logo,fit:'contain',position:'50% 50%'},hero:{type:'image',url:PM.sections.hero,fit:'cover',position:'50% 50%'},origin:{type:'image',url:PM.sections.origin,fit:'cover',position:'50% 50%'},atmosphere:{type:'image',url:PM.sections.atmosphere,fit:'cover',position:'50% 50%'},chef:{type:'image',url:PM.sections.chef,fit:'cover',position:'50% 50%'}},
  dishes:[
    {id:'pizza-margherita',name:'Margherita',meta:'Tomato · Fior di latte · Basil',short:'The reference pizza: tomato, fior di latte, basil and olive oil.',price:'€12',image:PM.pizzas.margherita,ingredients:'Tomato · fior di latte · basil · olive oil',origin:'Napoli-inspired · local ingredients',technique:'Long fermentation · high heat',pairing:'Lager / light red',note:'If the simplest pizza fails, the system has nothing to hide behind.',allergens:'Gluten · dairy',enabled:true},
    {id:'pizza-diavola',name:'Diavola',meta:'Tomato · Spicy salami · Chilli',short:'Tomato, fior di latte, spicy salami and chilli heat.',price:'€15',image:PM.pizzas.diavola,ingredients:'Tomato · fior di latte · spicy salami · chilli',origin:'Italian classic',technique:'High heat · crisp edge',pairing:'IPA / red wine',note:'Heat should arrive after the first bite, not before.',allergens:'Gluten · dairy',enabled:true},
    {id:'pizza-mortadella',name:'Mortadella & Pistachio',meta:'White · Mortadella · Pistachio',short:'White base, mortadella, stracciatella and pistachio.',price:'€17',image:PM.pizzas.mortadella,ingredients:'Fior di latte · mortadella · stracciatella · pistachio',origin:'Bologna-inspired',technique:'Bake first · cold finish',pairing:'Pilsner / sparkling',note:'Hot crust, cold topping, clean contrast.',allergens:'Gluten · dairy · nuts',enabled:true},
    {id:'pizza-tartufo',name:'Tartufo',meta:'White · Mushroom · Truffle',short:'Mushroom, fior di latte, parmesan and truffle aroma.',price:'€18',image:PM.pizzas.tartufo,ingredients:'Mushroom · fior di latte · parmesan · truffle',origin:'Seasonal',technique:'Roast · finish',pairing:'Amber beer / pinot noir',note:'Earthy, rich and intentionally simple.',allergens:'Gluten · dairy',enabled:true},
    {id:'pizza-marinara',name:'Marinara',meta:'Tomato · Garlic · Oregano',short:'Tomato, garlic, oregano and olive oil. No cheese.',price:'€10',image:PM.pizzas.marinara,ingredients:'Tomato · garlic · oregano · olive oil',origin:'Napoli classic',technique:'Fast bake · high heat',pairing:'Lager / vermouth',note:'A test of dough, tomato and oven.',allergens:'Gluten',enabled:true},
    {id:'pizza-quattro',name:'Quattro Formaggi',meta:'White · Four cheeses',short:'A richer white pizza built around four complementary cheeses.',price:'€16',image:PM.pizzas.quattro,ingredients:'Fior di latte · gorgonzola · taleggio · parmesan',origin:'Italian classic',technique:'Balanced melt',pairing:'Saison / white wine',note:'Intensity without becoming heavy.',allergens:'Gluten · dairy',enabled:true}
  ]
};